import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'it' | 'en' | 'hy' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const TRANSLATIONS: Record<string, any> = {
  it: {
    title: 'ItaliaGo',
    hotels: 'Hotel',
    restaurants: 'Ristoranti',
    tours: 'Tour',
    taxi: 'Taxi',
    discover: 'Scopri l\'Italia in modo più intelligente',
    companion: 'Il tuo compagno di fiducia per viaggi indimenticabili in tutta Italia.',
    start: 'Inizia il tuo viaggio',
    featured: 'Destinazioni in primo piano',
    wallet: 'Portafoglio',
    bonus: 'Bonus',
    filter: 'Filtra per',
    all: 'Tutti',
    more: 'Scopri di più',
    close: 'Chiudi',
    basket: 'Cestino',
    addToBasket: 'Aggiungi al cestino',
    priceRange: 'Prezzo',
    low: 'Economico',
    medium: 'Medio',
    high: 'Lusso',
    checkout: 'Pagamento',
    emptyBasket: 'Il tuo cestino è vuoto',
    experiences: 'Esperienze',
    rentals: 'Noleggi',
    events: 'Eventi',
    stories: 'Storie di Viaggio',
    reviews: 'Recensioni',
    leaveReview: 'Lascia una recensione',
    rating: 'Valutazione',
    comment: 'Commento',
    submit: 'Invia',
    noReviews: 'Ancora nessuna recensione.',
    privateTransport: 'Trasporto Privato',
    luxuryFingertips: 'Viaggi di lusso a portata di mano.',
    luxuryTier: 'Livello Lusso',
    findingDriver: 'Ricerca autista...',
    driverEnroute: 'L\'autista è in arrivo',
    driverArrived: 'L\'autista è arrivato!',
    connectingPartners: 'Connessione con partner premium a Roma.',
    rideWaiting: 'La tua corsa di lusso ti aspetta fuori.',
    requestNow: 'Richiedi ora',
    requesting: 'Richiesta in corso...',
    schedule: 'Programma',
    pickup: 'Punto di prelievo',
    destination: 'Destinazione',
    whereTo: 'Dove vuoi andare?',
    estCost: 'Costo stimato',
    estTime: 'Tempo stimato',
    distance: 'Distanza',
    traffic: 'Traffico',
    selectVehicle: 'Seleziona Veicolo',
    admin: 'Admin Panel',
    addListing: 'Add Listing',
    editListing: 'Edit Listing',
    deleteListing: 'Delete Listing',
    save: 'Save',
    cancel: 'Cancel',
    name: 'Name',
    location: 'Location',
    price: 'Price',
    type: 'Type',
    category: 'Category',
    stars: 'Stars',
    image: 'Image URL',
    description: 'Description',
    back: 'Indietro',
    botGreeting: 'Benvenuto! Sono il tuo Concierge ItaliaGo. Come posso rendere indimenticabile la tua fuga italiana oggi?',
    botPlaceholder: 'Chiedi al tuo concierge...',
  },
  en: {
    title: 'ItaliaGo',
    hotels: 'Hotels',
    restaurants: 'Restaurants',
    tours: 'Tours',
    taxi: 'Taxi',
    discover: 'Discover Italy Smarter',
    companion: 'Your trusted companion for unforgettable journeys across Italy.',
    start: 'Start Your Journey',
    featured: 'Featured Destinations',
    wallet: 'Wallet',
    bonus: 'Bonus',
    filter: 'Filter by',
    all: 'All',
    more: 'See More Info',
    close: 'Close',
    basket: 'Basket',
    addToBasket: 'Add to Basket',
    priceRange: 'Price',
    low: 'Budget',
    medium: 'Mid-range',
    high: 'Luxury',
    checkout: 'Checkout',
    emptyBasket: 'Your basket is empty',
    experiences: 'Experiences',
    rentals: 'Rentals',
    events: 'Events',
    stories: 'Travel Stories',
    reviews: 'Reviews',
    leaveReview: 'Leave a Review',
    rating: 'Rating',
    comment: 'Comment',
    submit: 'Submit',
    noReviews: 'No reviews yet.',
    privateTransport: 'Private Transport',
    luxuryFingertips: 'Luxury travel at your fingertips.',
    luxuryTier: 'Luxury Tier',
    findingDriver: 'Finding your driver...',
    driverEnroute: 'Driver is on the way',
    driverArrived: 'Driver has arrived!',
    connectingPartners: 'Connecting with premium partners in Roma.',
    rideWaiting: 'Your luxury ride is waiting outside.',
    requestNow: 'Request Now',
    requesting: 'Requesting...',
    schedule: 'Schedule',
    pickup: 'Pickup Location',
    destination: 'Destination',
    whereTo: 'Where to?',
    estCost: 'Est. Cost',
    estTime: 'Est. Time',
    distance: 'Distance',
    traffic: 'Traffic',
    selectVehicle: 'Select Vehicle',
    admin: 'Admin Panel',
    addListing: 'Add Listing',
    editListing: 'Edit Listing',
    deleteListing: 'Delete Listing',
    save: 'Save',
    cancel: 'Cancel',
    name: 'Name',
    location: 'Location',
    price: 'Price',
    type: 'Type',
    category: 'Category',
    stars: 'Stars',
    image: 'Image URL',
    description: 'Description',
    back: 'Back',
    botGreeting: 'Welcome! I am your ItaliaGo Concierge. How can I make your Italian escape unforgettable today?',
    botPlaceholder: 'Ask your concierge...',
  },
  hy: {
    title: 'ԻտալիաԳո',
    hotels: 'Հյուրանոցներ',
    restaurants: 'Ռեստորաններ',
    tours: 'Տուրեր',
    taxi: 'Տաքսի',
    discover: 'Բացահայտեք Իտալիան ավելի խելացի',
    companion: 'Ձեր վստահելի ուղեկիցը Իտալիայում անմոռանալի ճանապարհորդությունների համար:',
    start: 'Սկսեք ձեր ճանապարհորդությունը',
    featured: 'Առաջարկվող ուղղություններ',
    wallet: 'Քսակ',
    bonus: 'Բոնուս',
    filter: 'Ֆիլտրել ըստ',
    all: 'Բոլորը',
    more: 'Տեսնել ավելին',
    close: 'Փակել',
    basket: 'Զամբյուղ',
    addToBasket: 'Ավելացնել զամբյուղում',
    priceRange: 'Գին',
    low: 'Էժան',
    medium: 'Միջին',
    high: 'Թանկ',
    checkout: 'Վճարում',
    emptyBasket: 'Ձեր զամբյուղը դատարկ է',
    experiences: 'Փորձառություններ',
    rentals: 'Վարձույթ',
    events: 'Միջոցառումներ',
    stories: 'Ճամփորդական պատմություններ',
    reviews: 'Կարծիքներ',
    leaveReview: 'Թողնել կարծիք',
    rating: 'Գնահատական',
    comment: 'Մեկնաբանություն',
    submit: 'Ուղարկել',
    noReviews: 'Դեռևս կարծիքներ չկան:',
    privateTransport: 'Մասնավոր տրանսպորտ',
    luxuryFingertips: 'Լյուքս դասի ճանապարհորդություն ձեր մատների տակ:',
    luxuryTier: 'Լյուքս մակարդակ',
    findingDriver: 'Վարորդի որոնում...',
    driverEnroute: 'Վարորդը ճանապարհին է',
    driverArrived: 'Վարորդը ժամանել է:',
    findingPartners: 'Կապ հաստատել Հռոմի պրեմիում գործընկերների հետ:',
    rideWaiting: 'Ձեր լյուքս մեքենան սպասում է դրսում:',
    requestNow: 'Պատվիրել հիմա',
    requesting: 'Պատվիրվում է...',
    schedule: 'Պլանավորել',
    pickup: 'Վերցնելու վայրը',
    destination: 'Ուղղություն',
    whereTo: 'Ու՞ր եք ցանկանում գնալ:',
    estCost: 'Մոտավոր արժեքը',
    estTime: 'Մոտավոր ժամանակը',
    distance: 'Հեռավորությունը',
    traffic: 'Խցանումներ',
    selectVehicle: 'Ընտրել մեքենան',
    admin: 'Ադմինիստրատիվ պանել',
    addListing: 'Ավելացնել ցուցակ',
    editListing: 'Խմբագրել ցուցակը',
    deleteListing: 'Ջնջել ցուցակը',
    save: 'Պահպանել',
    cancel: 'Չեղարկել',
    name: 'Անուն',
    location: 'Վայր',
    price: 'Գին',
    type: 'Տեսակ',
    category: 'Կատեգորիա',
    stars: 'Աստղեր',
    image: 'Պատկերի URL',
    description: 'Նկարագրություն',
    back: 'Հետ',
    botGreeting: 'Բարի գալուստ: Ես ձեր ItaliaGo կոնսիերժն եմ: Ինչպե՞ս կարող եմ ձեր իտալական հանգիստն այսօր անմոռանալի դարձնել:',
    botPlaceholder: 'Հարցրեք ձեր կոնսիերժին...',
  },
  ru: {
    title: 'ИталияГо',
    hotels: 'Отели',
    restaurants: 'Рестораны',
    tours: 'Туры',
    taxi: 'Такси',
    discover: 'Откройте Италию умнее',
    companion: 'Ваш надежный спутник для незабываемых путешествий по всей Италии.',
    start: 'Начать путешествие',
    featured: 'Популярные направления',
    wallet: 'Кошелек',
    bonus: 'Бонус',
    filter: 'Фильтр по',
    all: 'Все',
    more: 'Подробнее',
    close: 'Закрыть',
    basket: 'Корзина',
    addToBasket: 'В корзину',
    priceRange: 'Цена',
    low: 'Бюджетно',
    medium: 'Средне',
    high: 'Люкс',
    checkout: 'Оплата',
    emptyBasket: 'Ваша корзина пуста',
    experiences: 'Впечатления',
    rentals: 'Аренда',
    events: 'События',
    stories: 'Истории путешествий',
    reviews: 'Отзывы',
    leaveReview: 'Оставить отзыв',
    rating: 'Рейтинг',
    comment: 'Комментарий',
    submit: 'Отправить',
    noReviews: 'Отзывов пока нет.',
    privateTransport: 'Частный транспорт',
    luxuryFingertips: 'Роскошные путешествия у вас под рукой.',
    luxuryTier: 'Люкс уровень',
    findingDriver: 'Поиск водителя...',
    driverEnroute: 'Водитель в пути',
    driverArrived: 'Водитель прибыл!',
    connectingPartners: 'Связь с премиум-партнерами в Риме.',
    rideWaiting: 'Ваша роскошная поездка ждет снаружи.',
    requestNow: 'Заказать сейчас',
    requesting: 'Заказ...',
    schedule: 'Запланировать',
    pickup: 'Место подачи',
    destination: 'Пункт назначения',
    whereTo: 'Куда едем?',
    estCost: 'Примерная стоимость',
    estTime: 'Примерное время',
    distance: 'Расстояние',
    traffic: 'Пробки',
    selectVehicle: 'Выберите транспорт',
    admin: 'Админ панель',
    addListing: 'Добавить объект',
    editListing: 'Редактировать объект',
    deleteListing: 'Удалить объект',
    save: 'Сохранить',
    cancel: 'Отмена',
    name: 'Название',
    location: 'Местоположение',
    price: 'Цена',
    type: 'Тип',
    category: 'Категория',
    stars: 'Звезды',
    image: 'URL изображения',
    description: 'Описание',
    back: 'Назад',
    botGreeting: 'Добро пожаловать! Я ваш консьерж ItaliaGo. Как я могу сделать ваш итальянский отдых незабываемым сегодня?',
    botPlaceholder: 'Спросите вашего консьержа...',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = TRANSLATIONS[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
